image: python:3.10

stages: # List of stages for jobs, and their order of execution
  - test
  - style


django-test-job: # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - python manage.py test

pylint-job:
  stage: style
  before_script:
    - pip install -r requirements.txt
  script:
    - pylint .
