# Generated by Django 4.1.5 on 2023-04-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0005_alter_event_finish_day_alter_event_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
