# Generated by Django 4.1.5 on 2023-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0006_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(to='fine.event'),
        ),
    ]
