# Generated by Django 4.1.4 on 2023-05-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0005_friends'),
        ('fine', '0007_user_events'),
    ]

    operations = [
    ]
