# Generated by Django 4.1.4 on 2023-05-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0007_merge_0005_friends_0006_alter_event_status'),
        ('fine', '0007_user_events'),
    ]

    operations = [
    ]
