# Generated by Django 4.1.4 on 2023-05-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0010_remove_event_entertainment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
