# Generated by Django 4.1.4 on 2023-05-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0012_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entertainment_type',
            field=models.IntegerField(choices=[(0, 'Sport'), (1, 'Meeting'), (2, 'Game'), (3, 'Entertainment')], default=1),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.IntegerField(choices=[(0, 'Sport'), (1, 'Meeting'), (2, 'Game'), (3, 'Entertainment')]),
        ),
    ]
