# Generated by Django 4.1.4 on 2023-05-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0014_remove_user_events_event_members_alter_event_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationevents',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registrationevents',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.DeleteModel(
            name='RegistrationEvents',
        ),
    ]
